// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $consultas_categorias from "./routes/consultas/categorias.tsx";
import * as $consultas_cursos from "./routes/consultas/cursos.tsx";
import * as $consultas_usuarios from "./routes/consultas/usuarios.tsx";
import * as $crear_categorias from "./routes/crear/categorias.tsx";
import * as $crear_cursos from "./routes/crear/cursos.tsx";
import * as $crear_usuarios from "./routes/crear/usuarios.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $ejecuciones from "./routes/ejecuciones.tsx";
import * as $historico from "./routes/historico.tsx";
import * as $index from "./routes/index.tsx";
import * as $jobs_id_ from "./routes/jobs/[id].tsx";
import * as $login from "./routes/login.tsx";
import * as $mantenimiento_categorias from "./routes/mantenimiento/categorias.tsx";
import * as $mantenimiento_cursos from "./routes/mantenimiento/cursos.tsx";
import * as $mantenimiento_usuarios from "./routes/mantenimiento/usuarios.tsx";
import * as $operaciones_ejecuciones from "./routes/operaciones/ejecuciones.tsx";
import * as $operaciones_historico from "./routes/operaciones/historico.tsx";
import * as $operaciones_index from "./routes/operaciones/index.tsx";
import * as $reportes from "./routes/reportes.tsx";
import * as $upload from "./routes/upload.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $CrearUsuarios from "./islands/CrearUsuarios.tsx";
import * as $CsvUploader from "./islands/CsvUploader.tsx";
import * as $DashboardIsland from "./islands/DashboardIsland.tsx";
import * as $ExecutionList from "./islands/ExecutionList.tsx";
import * as $FileUploader from "./islands/FileUploader.tsx";
import * as $HistoricoIsland from "./islands/HistoricoIsland.tsx";
import * as $JobDetailIsland from "./islands/JobDetailIsland.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $LoginPageIsland from "./islands/LoginPageIsland.tsx";
import * as $MetricsChart from "./islands/MetricsChart.tsx";
import * as $OperationHistorico from "./islands/OperationHistorico.tsx";
import * as $OperationList from "./islands/OperationList.tsx";
import * as $QueryTable from "./islands/QueryTable.tsx";
import * as $ReportesIsland from "./islands/ReportesIsland.tsx";
import * as $SemesterComparison from "./islands/SemesterComparison.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import * as $UploadIsland from "./islands/UploadIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/consultas/categorias.tsx": $consultas_categorias,
    "./routes/consultas/cursos.tsx": $consultas_cursos,
    "./routes/consultas/usuarios.tsx": $consultas_usuarios,
    "./routes/crear/categorias.tsx": $crear_categorias,
    "./routes/crear/cursos.tsx": $crear_cursos,
    "./routes/crear/usuarios.tsx": $crear_usuarios,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/ejecuciones.tsx": $ejecuciones,
    "./routes/historico.tsx": $historico,
    "./routes/index.tsx": $index,
    "./routes/jobs/[id].tsx": $jobs_id_,
    "./routes/login.tsx": $login,
    "./routes/mantenimiento/categorias.tsx": $mantenimiento_categorias,
    "./routes/mantenimiento/cursos.tsx": $mantenimiento_cursos,
    "./routes/mantenimiento/usuarios.tsx": $mantenimiento_usuarios,
    "./routes/operaciones/ejecuciones.tsx": $operaciones_ejecuciones,
    "./routes/operaciones/historico.tsx": $operaciones_historico,
    "./routes/operaciones/index.tsx": $operaciones_index,
    "./routes/reportes.tsx": $reportes,
    "./routes/upload.tsx": $upload,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/CrearUsuarios.tsx": $CrearUsuarios,
    "./islands/CsvUploader.tsx": $CsvUploader,
    "./islands/DashboardIsland.tsx": $DashboardIsland,
    "./islands/ExecutionList.tsx": $ExecutionList,
    "./islands/FileUploader.tsx": $FileUploader,
    "./islands/HistoricoIsland.tsx": $HistoricoIsland,
    "./islands/JobDetailIsland.tsx": $JobDetailIsland,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/LoginPageIsland.tsx": $LoginPageIsland,
    "./islands/MetricsChart.tsx": $MetricsChart,
    "./islands/OperationHistorico.tsx": $OperationHistorico,
    "./islands/OperationList.tsx": $OperationList,
    "./islands/QueryTable.tsx": $QueryTable,
    "./islands/ReportesIsland.tsx": $ReportesIsland,
    "./islands/SemesterComparison.tsx": $SemesterComparison,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
    "./islands/UploadIsland.tsx": $UploadIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
