"""add_detail_json_to_operation_items

Revision ID: 01187310a323
Revises: 3569d95539a4
Create Date: 2026-07-20 17:54:01.777038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01187310a323'
down_revision: Union[str, Sequence[str], None] = '3569d95539a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_items', sa.Column('detail', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_items', 'detail')
    # ### end Alembic commands ###
