"""add progress fields to executions

Revision ID: 1bc52da45165
Revises: fad979691ddc
Create Date: 2026-07-17 20:47:19.380076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc52da45165'
down_revision: Union[str, Sequence[str], None] = 'fad979691ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('current_phase', sa.String(length=100), nullable=True))
    op.add_column('executions', sa.Column('progress_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'progress_pct')
    op.drop_column('executions', 'current_phase')
    # ### end Alembic commands ###
