"""add_query_results_table

Revision ID: 3569d95539a4
Revises: 949234bd13ec
Create Date: 2026-07-20 14:37:42.407942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3569d95539a4'
down_revision: Union[str, Sequence[str], None] = '949234bd13ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_results_id'), 'query_results', ['id'], unique=False)
    op.create_index(op.f('ix_query_results_task_id'), 'query_results', ['task_id'], unique=True)
    op.add_column('operation_batches', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_batches', 'completed_at')
    op.drop_index(op.f('ix_query_results_task_id'), table_name='query_results')
    op.drop_index(op.f('ix_query_results_id'), table_name='query_results')
    op.drop_table('query_results')
    # ### end Alembic commands ###
