"""add_operation_batches_and_items

Revision ID: 949234bd13ec
Revises: 302bc957574b
Create Date: 2026-07-20 13:02:03.849595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949234bd13ec'
down_revision: Union[str, Sequence[str], None] = '302bc957574b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_batches_batch_id'), 'operation_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_operation_batches_id'), 'operation_batches', ['id'], unique=False)
    op.create_table('operation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['operation_batches.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_items_batch_id'), 'operation_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_operation_items_id'), 'operation_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_items_id'), table_name='operation_items')
    op.drop_index(op.f('ix_operation_items_batch_id'), table_name='operation_items')
    op.drop_table('operation_items')
    op.drop_index(op.f('ix_operation_batches_id'), table_name='operation_batches')
    op.drop_index(op.f('ix_operation_batches_batch_id'), table_name='operation_batches')
    op.drop_table('operation_batches')
    # ### end Alembic commands ###
