"""add phase_checkpoint to executions

Revision ID: cac79e1caadb
Revises: 01187310a323
Create Date: 2026-07-22 16:11:59.831025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac79e1caadb'
down_revision: Union[str, Sequence[str], None] = '01187310a323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('phase_checkpoint', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'phase_checkpoint')
    # ### end Alembic commands ###
